config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  match '404', to: 'index#page_not_found', via: :all
  match '422', to: 'index#page_not_found', via: :all
  match '500', to: 'index#page_broken', via: :all

  get :faq, to: "index#faq"

  get :flash_message, controller: "application"

  get 'talk' => 'index#get_request'
  post 'listen' => 'index#give_request'

  get 'freeplay' => 'users#freeplay'
  get 'register/step_2' => 'registrations#step_2', as: 'step_2'
  get 'register/step_3' => 'registrations#step_3', as: 'step_3'
  get 'register/step_4' => 'registrations#step_4', as: 'step_4'
  get 'register/step_5' => 'registrations#step_5', as: 'step_5'
  post 'register/step_2' => 'registrations#post_step_2'
  post 'register/step_3' => 'registrations#post_step_3'
  post 'register/step_4' => 'registrations#post_step_4'
  post 'register/step_4/fix' => 'registrations#fix_step_4', as: 'fix_review_page'
  post 'register/step_5' => 'registrations#post_step_5'

  # Websockets
  mount ActionCable.server => '/cable'

  resources :instructors do
    member do
      post :update_position
    end
  end

  get "/:slug" => "competitions#show", constraints: ->(request) { request.path_parameters[:slug].present? && Competition.from_slug(request.path_parameters[:slug]).present? }
  resources :competitions do
    get :export, on: :member
    get :monitor
    get :judge
    get :results
    get "judge/:category",              action: :category, as: :category
    get "judge/:category/:competitor_id",  action: :competitor, as: :competitor
    post "judge/:category/:competitor_id", action: :judge_competitor, as: :judge_competitor
  end
  resources :competitors, only: [:create, :update] do
    get :complete, on: :member
  end
  resources :spots
  resources :events, only: [ :show, :edit, :update ] do
    member do
      post :cancel
      get :detail
    end
  end
  resources :event_schedules, except: [ :destroy ] do
    get :contacts, on: :collection
    member do
      post :subscribe
      delete :unsubscribe
      post :send_message_to_subscribers
    end
  end

  resources :plan_items, except: [ :show, :destroy ]
  resources :line_items, except: [ :show ] do
    member do
      put :update_position
    end
  end

  resources :redemption_keys, except: [ :show, :edit, :update ] do
    member do
      get :redeem
    end
  end

  resources :class_handlers, path: 'class', only: [] do
    member do
      get :fast_pass_id
      get :fast_pass_pin
      get :logs
      post :join_class
    end
  end

  resources :announcements, except: [ :show ] do
    post :view, on: :collection
    post :deliver, on: :member
  end

  resources :attendances, only: [ :index, :new, :create, :destroy ]
  resources :aws_loggers, only: [ :index, :show ]
  resources :log_trackers, only: [ :index, :show ]
  resources :contact_requests, only: [ :index, :show ]
  resources :chat_rooms, path: "chat", only: [ :index, :show ] do
    get "phone_number/:phone_number", on: :collection, action: :by_phone_number, as: :phone_number
    post 'all/mark_messages_as_read', on: :collection, action: :mark_messages_as_read, as: :mark_messages_as_read
    resources :messages, only: [ :index ] do
      post :mark_messages_as_read, on: :collection
    end
  end

  get :dashboard, controller: :admins

  resource :admin, only: [] do
    get :purchase_history
    get :summary

    get :batch_text_message
    post :send_batch_texts

    get :email_body
    get :batch_email
    post :send_batch_emailer
  end

  resources :admin_users, path: "admin/users", only: [ :show, :index, :destroy ] do
    member do
      get :attendance
      get :unsubscribe_all
      post :update_trials
      post :update_credits
      post :update_notifications
    end
  end

  post 'contact' => 'index#contact'
  post 'receive_sms' => 'index#receive_sms'
  get 'contact' => 'index#contact_page', as: 'contact_page'
  post 'update' => 'index#update'
  get 'unsubscribe' => 'index#unsubscribe', as: 'unsubscribe_email'
  post 'unsubscribe' => 'index#unsubscribe_email', as: :unsubscribe
  post 'can_receive_sms' => 'index#can_receive_sms', as: 'make_can_receive_sms'

  delete 'unsubscribe_monthly/:id' => 'store#unsubscribe', as: 'unsubscribe_monthly_subscription'

  resources :athletes do
    member do
      post :reset_pin
      post :assign_plan
      delete :unsubscribe_plan
    end
    collection do
      post :verify
      post :assign_subscription
      patch :update_photo
    end
  end

  get 'waivers' => 'athletes#sign_waiver', as: 'waivers'
  post 'waivers' => 'athletes#update_waiver'
  post 'delete_athlete/:fast_pass_id' => 'athletes#delete_athlete'

  get "users/sign_up", action: "new", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  resource :user, except: [ :show ] do
    post :update_card_details
  end
  devise_for :users
  devise_scope :user do
    get "/account" => "users#edit"
  end
  post 'user/notifications/update' => 'index#update_notifications'

  get "/calendar/all", to: redirect("/calendar")
  get 'calendar' => 'calendar#show', as: 'calendar_show'
  get 'calendar/week' => 'calendar#get_week', as: 'week'
  get 'm/calendar' => 'calendar#mobile', as: 'calendar_mobile'
  get 'calendar/:city' => 'calendar#show'

  post 'store/charge' => 'store#charge', as: 'charge'
  get 'store' => 'store#index', as: 'store'
  post 'store/redeem' => 'store#redeem'

  post 'cart/update' => 'store#update_cart', as: 'update_cart'
  post 'cart/purchase' => 'store#purchase', as: 'purchase'

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

end

app/models/competition.rb
# == Schema Information
#
# Table name: competitions
#
#  id             :integer          not null, primary key
#  spot_id        :integer
#  name           :string
#  start_time     :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  slug           :string
#  description    :text
#  option_costs   :text
#  sponsor_images :text
#  coupon_codes   :text
#

# Add sponsor names, registration closure date
# ^^ Update index
class Competition < ApplicationRecord
  serialize :option_costs,   coder: JSONWrapper
  serialize :sponsor_images, coder: JSONWrapper
  serialize :coupon_codes,   coder: JSONWrapper

  belongs_to :spot, optional: true
  has_many :competitors

  before_save :set_slug

  scope :current, -> { where("start_time > ?", DateTime.current) }

  def self.from_slug(slug)
    find_by("LOWER(slug) = ?", slug.to_s.downcase)
  end

  def late_registration?(from_time=Time.current)
    from_time > start_time.beginning_of_week
  end

  def options
    @options ||= option_costs.deep_symbolize_keys
  end

  def show_description
    url_regex = /(https?:\/\/[\w\-\_\.\/~\$\&\+\,\/\:\;\=\?\@]+\.[\w\-\_\.\/~\$\&\+\,\/\:\;\=\?\@]+)/i
    description.gsub(url_regex) do |match|
      "<a href='#{match}' target='_blank'>#{match}</a>"
    end.html_safe
  end

  def registration_time
    late_registration? ? :late : :early
  end

  def select_options(age_group)
    options_list = options.dig(age_group, registration_time).to_a
    options_list += options.dig(age_group, :all).to_a
    options_list += options.dig(:all, :all).to_a

    options_list.uniq.map do |comp_name, price|
      ["#{comp_name} ($#{price})", comp_name]
    end
  end

  def age_groups
    options.keys
  end

  def cost_range
    return if option_costs.blank?
    options = option_costs.deep_symbolize_keys
    return "$#{options[:all]}" if options[:all].present? && !options[:all].is_a?(Hash)

    min = nil
    max = nil
    options.each do |age_group, registration_time|
      registration_time.presence&.each do |time, comps|
        comps.each do |name, price|
          min = price if min.nil? || price < min
          max = price if max.nil? || price > max
        end
      end
    end

    [min, max].compact.map { |price| "$#{price}" }.join("-")
  end

  def ranked_competitors(age_group, category=nil)
    category_competitors = competitors.approved.send(age_group).joins(:competition_judgements).distinct
    category_competitors.reject { |competitor| competitor.score(category).nil? }.sort_by { |competitor| -competitor.score(category) }
  end

  def competitor_hash
    categories = CompetitionJudgement.categories.keys
    competitors.approved.order(:sort_order).map do |competitor|
      hash = { id: competitor.id }
      categories.each do |category|
        hash[category] = competitor.score_display(category)
      end
      hash[:overall_impression] = competitor.score_display(:overall_impression)
      hash[:total] = competitor.score_display
      hash[:rank] = competitor.rank
      hash
    end
  end

  def to_param
    slug || id
  end

  private

  def set_slug
    self.slug = (self.slug.presence || name).parameterize
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :validate_instructor, except: [:index, :show]
  before_action :redirect_to_slug, only: :show

  def index
    @competitions = Competition.current.by_most_recent(:start_time)
  end

  def show
    return unless user_signed_in?

    @competitor = @competition.competitors.new
    @eligible_athletes = current_user.athletes.where.not(id: @competition.competitors.pluck(:athlete_id))
    @registered_athletes = current_user.athletes.where(id: @competition.competitors.pluck(:athlete_id))
  end

  def new
    @competition = Competition.new

    render :form
  end

  def edit
    @competition = comp_from_id

    render :form
  end

  def create
    @competition = Competition.new

    if @competition.update(competition_params)
      redirect_to @competition
    else
      render :form
    end
  end

  def update
    @competition = comp_from_id

    if @competition.update(competition_params)
      redirect_to @competition
    else
      render :form
    end
  end

  def destroy
    @competition = comp_from_id

    if @competition.destroy
      redirect_to :competitions
    else
      render :form
    end
  end

  def export
    @competition = comp_from_id
    @competitors = @competition.competitors.approved.order(:sort_order)
    csv_str = CSV.generate do |csv|
      csv << ["Name", "Age", "Years Training", "Instagram", "Song", "Bio"]
      @competitors.each do |c|
        csv << [c.full_name, c.age, c.years_training, c.instagram_handle, c.song, c.bio]
      end
    end
    send_data csv_str, filename: "competitors_export.csv"
  end

  def results
    competition = comp_from_id

    render json: competition.competitor_hash
  end

  def judge
    @competition = comp_from_id
  end

  def category
    @competition = comp_from_id
    @competitors = @competition.competitors.approved.order(:sort_order)
    @category = params[:category]
  end

  def competitor
    @competition = comp_from_id
    @competitor = @competition.competitors.find(params[:competitor_id])
    @category = params[:category]
  end

  def monitor
    @competition = comp_from_id
    @competitors = @competition.competitors.approved.order(:sort_order)
    @categories = CompetitionJudgement.categories.keys.map(&:titleize)
  end

  def judge_competitor
    @competition = comp_from_id
    @competitor = @competition.competitors.find(params[:competitor_id])
    @category = params[:category]

    judged = @competitor.competition_judgements.by_category(@category).first_or_initialize
    judged.judge = current_user
    judged.category_score = params.dig(:competition_judgement, :category_score)
    judged.overall_impression = params.dig(:competition_judgement, :overall_impression)
    judged.save

    redirect_to competition_category_path(@competition, @category)
  end

  private

  def comp_from_id
    id = params[:slug].presence || params[:id] || params[:competition_id]
    Competition.from_slug(id) || Competition.find(id)
  end

  def competition_params
    params.require(:competition).permit(
      :name,
      :slug,
      :start_time,
      :spot_id,
      :sponsor_images,
      :description,
      option_costs: {},
    )
  end

  def redirect_to_slug
    @competition = comp_from_id

    return if params[:slug].present?
    return redirect_to "/" + @competition.slug if @competition.try(:slug).present?

    redirect_to root_path, alert: "Competition not found" if @competition.nil?
  end
end

app/views/competitions/competitor.html.erb
<div class="judgement-page skinny-container">
  <h3 class="pull-right"><a href="<%= competition_category_path(@competition, @category) %>" class="pkut-text">Back</a></h3>
  <h2>Category - <%= @category.titleize %></h2>
  <div class="spaced-row">
    <h3><%= link_to @competitor.full_name, admin_user_path(@competitor.athlete.user_id) %></h3>
    <h5>
      Age: <%= @competitor.age || "?" %> | (<%= @competitor.athlete.date_of_birth %>) <br>
      <% if @competitor.years_training.present? %>
        Years training: <%= @competitor.years_training %> <br>
      <% end %>
      <% if @competitor.instagram_handle.present? %>
        Instagram: <%= link_to @competitor.instagram_handle, "https://www.instagram.com/#{@competitor.instagram_handle}" %> <br>
      <% end %>
      <% if @competitor.bio.present? %>
        Bio: <%= content_tag :pre, @competitor.bio %>
      <% end %>
    </h5>
  </div>

  <div class="text-center">
    <% judgement = @competitor.competition_judgements.by_category(@category).first_or_initialize %>
    <%= form_for judgement, url: competition_judge_competitor_path, method: :post, html: { class: "judge-form" } do |f| %>
      <h2><%= @category.upcase %></h2>
      <div class="text-field-wrapper">
        <%= f.text_field :category_score, placeholder: "00", value: judgement.category_score.to_s.gsub(/(\.)0+$/, '') %>
        <span>/20</span>
      </div>
      <h2>OVERALL IMPRESSION</h2>
      <div class="text-field-wrapper">
        <%= f.text_field :overall_impression, placeholder: "00", value: judgement.overall_impression.to_s.gsub(/(\.)0+$/, '') %>
        <span>/20</span>
      </div>
      <%= f.submit "Confirm", class: "hidden", id: "submit-judgment" %>
      <h3><%= link_to "Confirm", "#", class: "pkut-text", data: { modal: "#confirm-judgment" } %></h3>
    <% end %>
  </div>
</div>

<%= render_modal("confirm-judgment", "skinny-modal") do %>
  <h3><%= link_to @competitor.full_name, admin_user_path(@competitor.athlete.user_id) %></h3>
  <div class="scores">
    <div class="category">
      Flow: <span id="category_score">00</span>/20 points
    </div>
    <div class="overall_impression">
      Overall: <span id="overall_impression">00</span>/20 points
    </div>
  </div>
  <%= link_to "Confirm", "#", class: "pkut-btn", data: { clickit: "#submit-judgment" } %>
<% end %>

app/views/competitions/index.html.erb
<div class="competitions-wrapper central-container">
  <% if current_admin? %>
    <%= link_to "New Competition", new_competition_path, class: "pkut-btn" %>
  <% end %>
  <h3>Current Competitions:</h3>

  <% @competitions.each do |competition| %>
    <a href="<%= competition_path(competition) %>" class="competition-container" style="background-image: url(<%= asset_path('UniversityPlacePreview.png') %>)">
      <div class="title"><%= competition.name %></div>
      <div class="sponsors">
        Sponsored by: <br>
        YGT, University Place, &amp; Parkour Utah
      </div>
      <div class="details">
        <%= competition.age_groups.map(&:capitalize).to_sentence(last_word_connector: " & ", two_words_connector: " & ") %> <br>
        <%= competition.start_time.to_formatted_s(:simple) %>
      </div>
      <div class="cost"><%= competition.cost_range %></div>
      <!-- <div class="end-date">Registration Closes Sept 1st</div> -->
    </a>
  <% end %>
</div>

app/views/competitions/judge.html.erb
<div class="text-center judgement-page">
  <h2><%= @competition.name %>: <br> <%= @competition.start_time.strftime("%B %dth") %></h2>
  <h3>Category:</h3>
  <ul>
    <% CompetitionJudgement.categories.each do |category, _category_val| %>
      <li><h4><%= link_to category.titleize, competition_category_path(@competition, category) %></h4></li>
    <% end %>
  </ul>
  <br>
  <h4><%= link_to "Monitor", competition_monitor_path(@competition) %></h4>
</div>

app/views/competitions/show.html.erb
<div class="competition-wrapper">
  <% if current_admin? %>
    <%= link_to "Edit", edit_competition_path(@competition), class: "pkut-btn" %>
  <% end %>
  <% if current_instructor? %>
    <%= link_to "Judge Portal", competition_judge_path(@competition), class: "pkut-btn" %>
  <% end %>

  <h3><%= @competition.name %>: <br>
  <% if @competition.start_time.present? %>
    <%= @competition.start_time.strftime("%B %-dth") %> - <%= (@competition.start_time+1.day).strftime("%B %-dth") %></h3>
  <% end %>
  <h3><%= @competition.cost_range %></h3>
  <% sponsors = @competition.sponsor_images %>
  <% if sponsors&.any? %>
    <p>This Competition is brought to you by:</p>
    <div class="sponsors">
      <% count = sponsors.length %>
      <% sponsors.each_with_index do |sponsor_image, idx| %>
        <%= image_tag sponsor_image %>
        <%= "&" unless idx == count - 1 %>
      <% end %>
    </div>
  <% end %>
  <div class="description"><%= @competition.show_description %></div>
  <% if user_signed_in? %>
    <%= form_for @competitor, url: competitors_path do |f| %>
      <div class="form text-center">
        <div class="form-field">
          <% if @registered_athletes.any? %>
            <p><span class="pkut-text"><%= @registered_athletes.pluck(:full_name).to_sentence %></span> <%= @registered_athletes.one? ? "has" : "have" %> already been registered for this competition.</p>
          <% end %>
          <% if @eligible_athletes.none? %>
            <p class="pkut-text">You don't have any athletes eligible to enter this competition.</p>
          <% end %>
        </div>
        <% if @eligible_athletes.any? %>
          <%= f.hidden_field :competition_id %>
          <div class="form-field">
            <span class="pkut-text"><strong>Please add 1 athlete at a time.</strong></span>
            <%= f.select :athlete_id do %>
              <option>Select Athlete</option>
              <% @eligible_athletes.each do |athlete| %>
                <option value="<%= athlete.id %>" data-age-group="<%= athlete.age_group %>"><%= athlete.full_name %></option>
              <% end %>
            <% end %>
          </div>
          <div class="form-field">
            <% if @competition.options[:all].present? && @competition.options[:all].is_a?(Hash) %>
              <%= f.select :selected_comp, @competition.select_options(:all), {}, { class: "comp-select" } %>
            <% else %>
              <% [:youth, :adult].each do |age_group| %>
                <% if @competition.options[age_group].present? %>
                  <%= f.select :selected_comp, @competition.select_options(age_group), {}, { class: "comp-select", data: { reveal: age_group } } %>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <!-- <div class="form-field">
            <%#= f.select :shirt_size, ["Adult XS", "Adult S", "Adult M", "Adult L", "Adult XL"], include_blank: "Select Shirt Size" %>
          </div> -->
          <% if @competition.slug == "fitcon2023" %>
            <p class="comp-select-msg pkut-text hidden">Please use the checkboxes below to select the events you would like to participate in.</p>
            <div class="form-field hidden comp-selections" style="padding: 0 100px; text-align: left;">
              <div class="form-field">
                <div class="pkut-checkbox">
                  <%= f.check_box :signup_data, { multiple: true }, "TECHNIQUE", nil %>
                  <%= f.label :signup_data_technique, "TECHNIQUE" %>
                </div>
              </div>
              <div class="form-field">
                <div class="pkut-checkbox">
                  <%= f.check_box :signup_data, { multiple: true }, "SPEED", nil %>
                  <%= f.label :signup_data_speed, "SPEED" %>
                </div>
              </div>
              <div class="form-field">
                <div class="pkut-checkbox">
                  <%= f.check_box :signup_data, { multiple: true }, "FREESTYLE", nil %>
                  <%= f.label :signup_data_freestyle, "FREESTYLE" %>
                </div>
              </div>
              <div class="form-field">
                <div class="pkut-checkbox">
                  <%= f.check_box :signup_data, { multiple: true }, "ALL THREE", nil %>
                  <%= f.label :signup_data_all_three, "ALL THREE" %>
                </div>
              </div>
            </div>
            <script type="text/javascript">
              $(document).ready(function() {
                let updateSelectedComp = function() {
                  let check_count = $(".comp-selections input").filter(function() {
                    return $(this).prop("checked")
                  }).length

                  if (check_count > 3) { check_count = 3 }
                  if (check_count < 1) { return }

                  $(".comp-select").each(function() {
                    $(this).val($(this).find("option")[check_count-1].value)
                  })
                }

                $(".comp-select").on("keydown mousedown touchstart", function(evt) {
                  $(".comp-select-msg").removeClass("hidden")
                  evt.preventDefault()
                })

                $("#competitor_athlete_id").change(function() {
                  $(".comp-selections").removeClass("hidden")
                })

                $("#competitor_signup_data_all_three").change(function() {
                  $(".comp-selections input").prop("checked", $(this).prop("checked"))
                })
                $(".comp-selections input").change(function() {
                  updateSelectedComp()
                })
              })
            </script>
          <% end %>
          <div class="form-field"><%= f.text_field :instagram_handle, placeholder: "Instagram Handle", class: "pkut-textbox disableEnterSubmit" %></div>
          <div class="form-field"><%= f.text_field :song, placeholder: "Song (family friendly - leave blank for random)", class: "pkut-textbox disableEnterSubmit" %></div>
          <div class="form-field"><%= f.text_area :bio, placeholder: "Bio (140 character limit)", class: "pkut-textarea", maxlength: "140" %></div>
          <div class="form-field"><%= f.text_field :referred_by, placeholder: "Referred By", class: "pkut-textbox disableEnterSubmit" %></div>
          <div class="form-field"><%= f.text_field :coupon_code, placeholder: "Coupon Code", class: "pkut-textbox disableEnterSubmit" %></div>
        <% end %>
      </div>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-image="http://parkourutah.com/favicon.ico"
              data-name="Parkour Utah"
              data-billing-address="true"
              data-description="All Sales are Final">
      </script>
    <% end %>
    <p class="text-center">
      <%= link_to "", class: "pkut-btn #{'disabled' if @competitor.athlete_id.blank?}", id: "form-submit", data: { toggle: "modal", target: "#waiver_modal" } do %>
        Register Competitor <span class="competitor-cost"></span>
      <% end %>
    </p>
  <% else %>
    <p>Please sign in or register before enrolling in the competition.</p>
    <p class="text-center">
      <%= link_to "Sign in", new_user_session_path, class: "pkut-btn" %>
      <%= link_to "Register", new_user_path, class: "pkut-btn" %>
    </p>
  <% end %>
</div>

<%= render_modal("waiver_modal", "medium-modal text-left") do %>
  <h2 class="title">Waiver</h2>
  <div class="row">
    <div class="col-sm-4">This waiver is for</div>
    <div class="col-sm-8 waiver-athletes"></div>
  </div>
  <br/>
  <p>If this information is incorrect please click the red X on the top right and update the information before attempting to sign the waiver again.</p>
  <div class="text-center">
    <%= link_to 'REVIEW AND DOWNLOAD WAIVER', '//s3-us-west-2.amazonaws.com/pkut-default/PKUT+UP+Woodbury+Corp+Waiver.pdf', class: 'pkut-link', target: '_blank' %>
    <br>
    <div class="pkut-checkbox center-checkbox">
      <%= check_box_tag :signed, '', nil, class: 'required-checkbox' %>
      <%= label_tag :signed do %>
        <div class="arrow-required">Required</div>
      <% end %>
    </div>
  </div>
  <p>By checking the box above, I hereby agree to waive any liability of Parkour Utah and it's affiliated organizations for the athletes listed above. By entering my name below, I certify that I have downloaded, read, and understand all of the terms and provisions in the liability waiver document available for download above.</p>
  <p>I also certify that I understand that the above document that I have downloaded and read is a legal document, and it is my understanding that an electronic signature has the same effect and can be enforced in the same way as a writen signature, as stated in Utah Code 46-4-201.</p>
  <p>By signing this document, I am waiving any liability claims against Parkour Utah and it's affiliated organizations for the athlete selected, and certify that I am the athlete or the parent and/or guardian of the athlete, and I am waiving any liability claims against Parkour Utah and it's affiliated organizations on behalf of the athletes listed above.</p>
  <br/>
  <div class="text-center">
    <%= text_field_tag :signed_by, '', placeholder: 'Signed By', class: 'pkut-textbox customRequired', autocomplete: 'off' %>
    <br/>
    <%= link_to "Submit", "", class: "pkut-btn disabled", id: "waiver-submit", data: { clickit: ".stripe-button-el", dismiss: :modal } %>
  </div>
<% end %>

<% if current_user&.admin? %>
  <div class="small-container" style="margin: 0 auto;">
    <p>Registered competitors (only admins see this section)</p>
    <p class="text-center">
      <%= link_to "Export to CSV", export_competition_path(@competition), download: true, class: "pkut-btn" %>
    </p>
    <ul>
    <% @competition.competitors.order("approved_at NULLS FIRST, created_at DESC").each do |competitor| %>
      <% next unless competitor.persisted? %>
      <li>
        <%= link_to "#{competitor.athlete_id}: #{competitor.athlete.full_name}", admin_user_path(competitor.athlete.user) %>
        <ul>
          <% if competitor.approved_at? %>
            <li style="color: green;">Approved</li>
          <% else %>
            <li><%= link_to "Approve this athlete", competitor_path(competitor), method: :patch, data: { confirm: "Are you sure?" } unless competitor.approved_at? %></li>
          <% end %>
          <li><strong>Age:</strong> <%= competitor.age %></li>
          <li><strong>Years:</strong> <%= competitor.years_training %></li>
          <li><strong>Instagram:</strong> <%= link_to competitor.instagram_handle, "https://www.instagram.com/#{competitor.instagram_handle}" if competitor.instagram_handle %></li>
          <li><strong>Song:</strong> <%= competitor.song %></li>
          <li><strong>Referred By:</strong> <%= competitor.referred_by %></li>
          <li><strong>Bio:</strong> <%= content_tag :pre, competitor.bio if competitor.bio.present? %></li>
          <li><strong>Competition:</strong> <%= competitor.competition.name %></li>
          <li><strong>Category:</strong> <%= competitor.selected_comp %></li>
          <% if @competition.age_groups.many? %>
            <li><strong>Age Group:</strong> <%= competitor.age_group.to_s.titleize %> (<%= competitor.age_group == :adult ? "14+" : "Under 14" %>)</li>
          <% end %>
          <% if competitor.shirt_size.present? %>
            <li><strong>Shirt Size:</strong> <%= competitor.shirt_size %></li>
          <% end %>
          <li><strong>Referred by:</strong> <%= competitor.referred_by %></li>
          <li><strong>Payment Received:</strong> $<%= competitor.discounted_cost %> <%= "(#{competitor.coupon_code})" if competitor.coupon_code.present? %></li>
          <% if competitor.signup_data.present? %>
            <li><strong>Selected Comps:</strong> <%= competitor.signup_data.join(", ") %></li>
          <% end %>

          <% if competitor.stripe_charge_id.present? %>
            <li><%= link_to "View in Stripe", "https://dashboard.stripe.com/payments/#{competitor.stripe_charge_id}" %></li>
          <% else %>
            <li><strong>Sponsored Athlete - no payment</strong></li>
          <% end %>
        </ul>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>