config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  match '404', to: 'index#page_not_found', via: :all
  match '422', to: 'index#page_not_found', via: :all
  match '500', to: 'index#page_broken', via: :all

  get :faq, to: "index#faq"

  get :flash_message, controller: "application"

  get 'talk' => 'index#get_request'
  post 'listen' => 'index#give_request'

  get 'freeplay' => 'users#freeplay'
  get 'register/step_2' => 'registrations#step_2', as: 'step_2'
  get 'register/step_3' => 'registrations#step_3', as: 'step_3'
  get 'register/step_4' => 'registrations#step_4', as: 'step_4'
  get 'register/step_5' => 'registrations#step_5', as: 'step_5'
  post 'register/step_2' => 'registrations#post_step_2'
  post 'register/step_3' => 'registrations#post_step_3'
  post 'register/step_4' => 'registrations#post_step_4'
  post 'register/step_4/fix' => 'registrations#fix_step_4', as: 'fix_review_page'
  post 'register/step_5' => 'registrations#post_step_5'

  # Websockets
  mount ActionCable.server => '/cable'

  resources :instructors do
    member do
      post :update_position
    end
  end

  get "/:slug" => "competitions#show", constraints: ->(request) { request.path_parameters[:slug].present? && Competition.from_slug(request.path_parameters[:slug]).present? }
  resources :competitions do
    get :export, on: :member
    get :monitor
    get :judge
    get :results
    get "judge/:category",              action: :category, as: :category
    get "judge/:category/:competitor_id",  action: :competitor, as: :competitor
    post "judge/:category/:competitor_id", action: :judge_competitor, as: :judge_competitor
  end
  resources :competitors, only: [:create, :update] do
    get :complete, on: :member
  end
  resources :spots
  resources :events, only: [ :show, :edit, :update ] do
    member do
      post :cancel
      get :detail
    end
  end
  resources :event_schedules, except: [ :destroy ] do
    get :contacts, on: :collection
    member do
      post :subscribe
      delete :unsubscribe
      post :send_message_to_subscribers
    end
  end

  resources :plan_items, except: [ :show, :destroy ]
  resources :line_items, except: [ :show ] do
    member do
      put :update_position
    end
  end

  resources :redemption_keys, except: [ :show, :edit, :update ] do
    member do
      get :redeem
    end
  end

  resources :class_handlers, path: 'class', only: [] do
    member do
      get :fast_pass_id
      get :fast_pass_pin
      get :logs
      post :join_class
    end
  end

  resources :announcements, except: [ :show ] do
    post :view, on: :collection
    post :deliver, on: :member
  end

  resources :attendances, only: [ :index, :new, :create, :destroy ]
  resources :aws_loggers, only: [ :index, :show ]
  resources :log_trackers, only: [ :index, :show ]
  resources :contact_requests, only: [ :index, :show ]
  resources :chat_rooms, path: "chat", only: [ :index, :show ] do
    get "phone_number/:phone_number", on: :collection, action: :by_phone_number, as: :phone_number
    post 'all/mark_messages_as_read', on: :collection, action: :mark_messages_as_read, as: :mark_messages_as_read
    resources :messages, only: [ :index ] do
      post :mark_messages_as_read, on: :collection
    end
  end

  get :dashboard, controller: :admins

  resource :admin, only: [] do
    get :purchase_history
    get :summary

    get :batch_text_message
    post :send_batch_texts

    get :email_body
    get :batch_email
    post :send_batch_emailer
  end

  resources :admin_users, path: "admin/users", only: [ :show, :index, :destroy ] do
    member do
      get :attendance
      get :unsubscribe_all
      post :update_trials
      post :update_credits
      post :update_notifications
    end
  end

  post 'contact' => 'index#contact'
  post 'receive_sms' => 'index#receive_sms'
  get 'contact' => 'index#contact_page', as: 'contact_page'
  post 'update' => 'index#update'
  get 'unsubscribe' => 'index#unsubscribe', as: 'unsubscribe_email'
  post 'unsubscribe' => 'index#unsubscribe_email', as: :unsubscribe
  post 'can_receive_sms' => 'index#can_receive_sms', as: 'make_can_receive_sms'

  delete 'unsubscribe_monthly/:id' => 'store#unsubscribe', as: 'unsubscribe_monthly_subscription'

  resources :athletes do
    member do
      post :reset_pin
      post :assign_plan
      delete :unsubscribe_plan
    end
    collection do
      post :verify
      post :assign_subscription
      patch :update_photo
    end
  end

  get 'waivers' => 'athletes#sign_waiver', as: 'waivers'
  post 'waivers' => 'athletes#update_waiver'
  post 'delete_athlete/:fast_pass_id' => 'athletes#delete_athlete'

  get "users/sign_up", action: "new", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  resource :user, except: [ :show ] do
    post :update_card_details
  end
  devise_for :users
  devise_scope :user do
    get "/account" => "users#edit"
  end
  post 'user/notifications/update' => 'index#update_notifications'

  get "/calendar/all", to: redirect("/calendar")
  get 'calendar' => 'calendar#show', as: 'calendar_show'
  get 'calendar/week' => 'calendar#get_week', as: 'week'
  get 'm/calendar' => 'calendar#mobile', as: 'calendar_mobile'
  get 'calendar/:city' => 'calendar#show'

  post 'store/charge' => 'store#charge', as: 'charge'
  get 'store' => 'store#index', as: 'store'
  post 'store/redeem' => 'store#redeem'

  post 'cart/update' => 'store#update_cart', as: 'update_cart'
  post 'cart/purchase' => 'store#purchase', as: 'purchase'

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :validate_admin

  def index
    @instructors = User.instructors.order(instructor_position: :asc)
  end

  def show
    @instructor = User.instructors.find(params[:id])
  end

  def new
    @instructor = User.new
  end

  def create
    new_pass = "UTPKFR4LF"
    new_user = false
    instructor = User.find_by_email(params[:user][:email])
    new_user = true if instructor.nil?
    instructor ||= User.new(email: params[:user][:email], password: new_pass)
    instructor.update(instructor_params)
    if instructor.save
      number_of_instructors = User.instructors.count
      instructor.update(role: 1, instructor_position: number_of_instructors + 1)
      flash[:notice] = "Instructor successfully created with password: #{new_pass}." if new_user == true
      flash[:notice] = "Instructor successfully promoted." if new_user == false
    else
      flash[:alert] = "There was an error adding the instructor."
    end
    redirect_to instructors_path
  end

  def edit
    @instructor = User.instructors.find(params[:id])
  end

  def update
    if User.find(params[:id]).update(instructor_params)
      flash[:notice] = "Instructor successfully updated."
    else
      flash[:alert] = "There was an error updating the instructor."
    end
    redirect_to instructors_path
  end

  def destroy
    @instructor = User.instructors.find(params[:id])
    if @instructor.update(role: 0)
      User.update_instructor_positions
      redirect_to instructors_path, notice: "Successfully demoted Instructor"
    else
      redirect_to instructors_path, alert: "There was an error demoting that Instructor."
    end
  end

  def update_position
    @instructor = User.find(params[:id])
    @instructor.update(instructor_position: params["instructor"]["instructor_position"].to_i)
    respond_to do |format|
      format.json { render json: @instructor }
    end
  end

  private

  def instructor_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :nickname,
      :stats,
      :title,
      :bio,
      :avatar,
      :avatar_2,
      :role,
      :should_display_on_front_page
    )
  end

end

app/views/instructors/_form.html.erb
<div class="central-container form-offset">
  <%= link_to "Back to Dashboard", dashboard_path, class: 'pkut-btn' %> <br>
  <% if @instructor.persisted? %>
    <%= link_to "View Instructor Attendances", instructor_path(@instructor), class: 'pkut-btn' %>
  <% end %>
  <% path = @instructor.persisted? ? instructor_path(@instructor) : instructors_path %>
  <%= form_for @instructor, url: path do |f| %>
    <div class="form-container">
      <% if @instructor.persisted? %>
        <div class="form-field">
          <%= f.label :email %> <br>
          <%= f.text_field :email, placeholder: 'justin@parkourutah.com', class: 'pkut-textbox' %>
        </div>
      <% else %>
        <div class="form-field">
          <%= f.label :email, "Enter an existing users email or a new account will be created for them." %> <br>
          <%= f.text_field :email, placeholder: 'justin@parkourutah.com', class: 'pkut-textbox' %>
        </div>
      <% end %>
      <div class="form-field">
        <%= f.label :first_name %> <br>
        <%= f.text_field :first_name, placeholder: 'Justin', class: 'pkut-textbox' %>
      </div>
      <div class="form-field">
        <%= f.label :last_name %> <br>
        <%= f.text_field :last_name, placeholder: 'Spencer', class: 'pkut-textbox' %>
      </div>
      <div class="form-field">
        <%= f.label :nickname %>(Optional) <br>
        <%= f.text_field :nickname, placeholder: 'Captain Awesome', class: 'pkut-textbox' %>
      </div>
      <div class="form-field">
        <%= f.label :title %> <br>
        <%= f.text_field :title, placeholder: 'Instructor', class: 'pkut-textbox' %>
      </div>
      <div class="form-field">
        <%= f.label :stats %> <br>
        <%= f.text_field :stats, placeholder: '5\'10" 180 lbs', class: 'pkut-textbox' %>
      </div>
      <div class="form-field">
        <%= f.label :bio %> <br>
        <%= f.text_area :bio, rows: '12', maxlength: '550', class: 'pkut-textarea restrictBio' %>
      </div>
      <div class="form-field">
        <%= f.label :avatar, 'Front Image' %> <br>
        <%= f.file_field :avatar %>
      </div>
      <div class="form-field">
        <%= f.label :avatar_2, 'Back Image' %> <br>
        <%= f.file_field :avatar_2 %>
      </div>
      <div class="form-field" style="margin-top: 10px;">
        <div class="pkut-checkbox">
          <%= f.check_box :should_display_on_front_page %>
          <%= f.label :should_display_on_front_page, "Should Display on front page?" %>
        </div>
      </div>
      <%= f.submit "Submit", class: 'btn btn-success' %>
      <% if @instructor.is_instructor? %>
        <%= link_to "Demote", instructor_path(@instructor), class: 'btn btn-danger', method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/instructors/edit.html.erb
<%= render partial: 'form' %>

app/views/instructors/index.html.erb
<div class="central-container form-offset">
  <%= link_to "Back to Dashboard", dashboard_path, class: 'pkut-btn' %><br/>
  <%= link_to new_instructor_path, class: 'pkut-btn' do %>
    <i class="fa fa-plus"></i> New Instructor
  <% end %>
  <h4>Click and Drag to change Instructor order. Click to edit Instructor info.</h4>
  <table class="sortable" id="instructor-table">
    <% @instructors.each do |instructor| %>
      <tr class="sortable-row">
        <td class="hidden sortable-url"><%= update_position_instructor_path(instructor) %></td>
        <td>
          <%= link_to edit_instructor_path(instructor), class: 'pkut-btn' do %>
            <i class="fa fa-arrows fa-lg"></i>
            <%= instructor.full_name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/instructors/new.html.erb
<%= render partial: 'form' %>

app/views/instructors/show.html.erb
<div class="central-container">
  <%= link_to "Back to Dashboard", dashboard_path, class: 'pkut-btn' %>
  <h1><%= @instructor.full_name %></h1>
  <%= link_to new_attendance_path(instructor_id: @instructor.id), class: "pkut-btn" do %>
    <i class="fa fa-plus"></i> Add Attendance
  <% end %>
  <% @instructor.attendances_taught.order(created_at: :desc).group_by {|a| a.created_at.to_date}.each do |date, attendances| %>
    <h3><%= date.strftime("%B %-d, %Y") %></h3>
    <ul>
      <% attendances.each do |attendance| %>
        <% next unless attendance.athlete.present? %>
        <li style="margin-top: 10px;">
          <strong>Class:</strong> <%= link_to attendance.event.title, event_schedule_path(attendance.event.event_schedule) %><br>
          <strong>Student:</strong> <%= link_to attendance.athlete.full_name, admin_user_path(attendance.athlete.user) %><br>
          <strong>Guardian:</strong> <%= link_to attendance.athlete.user.email, admin_user_path(attendance.athlete.user) %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>