config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  match '404', to: 'index#page_not_found', via: :all
  match '422', to: 'index#page_not_found', via: :all
  match '500', to: 'index#page_broken', via: :all

  get :faq, to: "index#faq"

  get :flash_message, controller: "application"

  get 'talk' => 'index#get_request'
  post 'listen' => 'index#give_request'

  get 'freeplay' => 'users#freeplay'
  get 'register/step_2' => 'registrations#step_2', as: 'step_2'
  get 'register/step_3' => 'registrations#step_3', as: 'step_3'
  get 'register/step_4' => 'registrations#step_4', as: 'step_4'
  get 'register/step_5' => 'registrations#step_5', as: 'step_5'
  post 'register/step_2' => 'registrations#post_step_2'
  post 'register/step_3' => 'registrations#post_step_3'
  post 'register/step_4' => 'registrations#post_step_4'
  post 'register/step_4/fix' => 'registrations#fix_step_4', as: 'fix_review_page'
  post 'register/step_5' => 'registrations#post_step_5'

  # Websockets
  mount ActionCable.server => '/cable'

  resources :instructors do
    member do
      post :update_position
    end
  end

  get "/:slug" => "competitions#show", constraints: ->(request) { request.path_parameters[:slug].present? && Competition.from_slug(request.path_parameters[:slug]).present? }
  resources :competitions do
    get :export, on: :member
    get :monitor
    get :judge
    get :results
    get "judge/:category",              action: :category, as: :category
    get "judge/:category/:competitor_id",  action: :competitor, as: :competitor
    post "judge/:category/:competitor_id", action: :judge_competitor, as: :judge_competitor
  end
  resources :competitors, only: [:create, :update] do
    get :complete, on: :member
  end
  resources :spots
  resources :events, only: [ :show, :edit, :update ] do
    member do
      post :cancel
      get :detail
    end
  end
  resources :event_schedules, except: [ :destroy ] do
    get :contacts, on: :collection
    member do
      post :subscribe
      delete :unsubscribe
      post :send_message_to_subscribers
    end
  end

  resources :plan_items, except: [ :show, :destroy ]
  resources :line_items, except: [ :show ] do
    member do
      put :update_position
    end
  end

  resources :redemption_keys, except: [ :show, :edit, :update ] do
    member do
      get :redeem
    end
  end

  resources :class_handlers, path: 'class', only: [] do
    member do
      get :fast_pass_id
      get :fast_pass_pin
      get :logs
      post :join_class
    end
  end

  resources :announcements, except: [ :show ] do
    post :view, on: :collection
    post :deliver, on: :member
  end

  resources :attendances, only: [ :index, :new, :create, :destroy ]
  resources :aws_loggers, only: [ :index, :show ]
  resources :log_trackers, only: [ :index, :show ]
  resources :contact_requests, only: [ :index, :show ]
  resources :chat_rooms, path: "chat", only: [ :index, :show ] do
    get "phone_number/:phone_number", on: :collection, action: :by_phone_number, as: :phone_number
    post 'all/mark_messages_as_read', on: :collection, action: :mark_messages_as_read, as: :mark_messages_as_read
    resources :messages, only: [ :index ] do
      post :mark_messages_as_read, on: :collection
    end
  end

  get :dashboard, controller: :admins

  resource :admin, only: [] do
    get :purchase_history
    get :summary

    get :batch_text_message
    post :send_batch_texts

    get :email_body
    get :batch_email
    post :send_batch_emailer
  end

  resources :admin_users, path: "admin/users", only: [ :show, :index, :destroy ] do
    member do
      get :attendance
      get :unsubscribe_all
      post :update_trials
      post :update_credits
      post :update_notifications
    end
  end

  post 'contact' => 'index#contact'
  post 'receive_sms' => 'index#receive_sms'
  get 'contact' => 'index#contact_page', as: 'contact_page'
  post 'update' => 'index#update'
  get 'unsubscribe' => 'index#unsubscribe', as: 'unsubscribe_email'
  post 'unsubscribe' => 'index#unsubscribe_email', as: :unsubscribe
  post 'can_receive_sms' => 'index#can_receive_sms', as: 'make_can_receive_sms'

  delete 'unsubscribe_monthly/:id' => 'store#unsubscribe', as: 'unsubscribe_monthly_subscription'

  resources :athletes do
    member do
      post :reset_pin
      post :assign_plan
      delete :unsubscribe_plan
    end
    collection do
      post :verify
      post :assign_subscription
      patch :update_photo
    end
  end

  get 'waivers' => 'athletes#sign_waiver', as: 'waivers'
  post 'waivers' => 'athletes#update_waiver'
  post 'delete_athlete/:fast_pass_id' => 'athletes#delete_athlete'

  get "users/sign_up", action: "new", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  resource :user, except: [ :show ] do
    post :update_card_details
  end
  devise_for :users
  devise_scope :user do
    get "/account" => "users#edit"
  end
  post 'user/notifications/update' => 'index#update_notifications'

  get "/calendar/all", to: redirect("/calendar")
  get 'calendar' => 'calendar#show', as: 'calendar_show'
  get 'calendar/week' => 'calendar#get_week', as: 'week'
  get 'm/calendar' => 'calendar#mobile', as: 'calendar_mobile'
  get 'calendar/:city' => 'calendar#show'

  post 'store/charge' => 'store#charge', as: 'charge'
  get 'store' => 'store#index', as: 'store'
  post 'store/redeem' => 'store#redeem'

  post 'cart/update' => 'store#update_cart', as: 'update_cart'
  post 'cart/purchase' => 'store#purchase', as: 'purchase'

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

end

app/views/index/_contact_us.html.erb
<div class="central-container pkut-box clearfix contact-us">
  <h2 class="header-text">Contact Us</h2>
  <div class="text-center">Let us know if you have any questions about classes, private lessons, what we do, etc...</div>
  <div class="contact-links">
    <a rel="nofollow external" target="_blank" href="https://www.facebook.com/ParkourUtah/" class="contact-link"><%= image_tag "Facebook.png" %></a>
    <a rel="nofollow external" target="_blank" href="https://twitter.com/parkourutah" class="contact-link"><%= image_tag "Twitter.png" %></a>
    <a rel="nofollow external" target="_blank" href="https://www.youtube.com/parkourutah" class="contact-link"><%= image_tag "Youtube.png" %></a>
    <a rel="nofollow external" target="_blank" href="https://www.instagram.com/parkourutah/" class="contact-link"><%= image_tag "Instagram.png" %></a>
  </div>
  <p class="text-center contact-or">- or -</p>
  <%= form_tag "/contact" do %>
    <%= hidden_field_tag :enabled, false, class: 'enabled-field' %>
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <%= text_field_tag :name, '', class: 'pkut-textbox', placeholder: 'Your Name' %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= text_field_tag :email, '', class: 'pkut-textbox', placeholder: 'Email' %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= telephone_field_tag :phone, '', class: 'pkut-textbox formatPhoneNumber customRequired', placeholder: 'Phone (required)' %><br/>
      </div>
    </div>
    <p class="text-center">Questions about classes? Be sure to check our <a href="<%= faq_path %>">FAQ</a>!</p>
    <%= text_area_tag :comment, '', class: 'pkut-textarea', maxlength: 600, placeholder: "Comments, questions, inquiries, interrogations, conversations, queries, chatter, information annex, whatever you need to know type it here and we'll get back to you A.S.A.P.P. (As Soon As Parkour Possible)" %>
    <%= button_tag "Send", class: "pkut-btn pull-right" %>
  <% end %>
</div>

app/views/index/coming_soon.html.erb
<div class="central-container form-offset">
<h2>Sorry! This page is unavailable at this time.</h2>
<br/>
<h3>Come back and check it out later!</h3>
</div>

app/views/index/contact_page.html.erb
<div class="form-offset">
  <%= render partial: 'index/contact_us' %>
</div>

app/views/index/faq.html.erb
<div class="central-container faq-page">
  <div class="faq-question">How Do I Sign Up?</div>

  <p class="faq-answer">
    Click on the <span style="color: red;">RED</span> <a href="<%= new_user_registration_path %>">get started button</a> on our front page. From there go through the registration process making sure to sign a waiver for <strong>each</strong> participant. If you are under 18 you will need a parent or guardian to complete the form for you. At the end of the registration process there is an automated email with your assigned Athlete ID and your customized PIN. Put both in the flashing box to receive your free trial classes. <strong>Remember to bring both numbers to class in order to attend.</strong>
  </p>

  <div class="faq-question">I can't make it to class this week, what do I need to do?</div>

  <div class="faq-answer">Your credits can be used on any class at any date. Credits don't expire, so you don't need to worry about missing a class or switching to a different location.</div>

  <div class="faq-question">What Ages Do You Teach?</div>

  <p class="faq-answer">
    For now we teach ages 7+. Make sure to pay attention to our facebook page and keep looking at our occasional emails, we're planning on setting up 3-6 year old classes soon as well as adult specific classes!
  </p>

  <div class="faq-question">How Much Are Classes/What are Credits?</div>

  <p class="faq-answer">
    The first class is offered for free as a trial.
    <br>
    Following your one free class, they are $12 each. There are bulk discounts in the store as well as open gym and any events we may offer. Each dollar gets you a <strong>credit</strong> and credits can be applied to any class, open gym, or event.
  </p>

  <div class="faq-question">Where Can I Take Classes?</div>

  <p class="faq-answer">
    Check our <a href="<%= calendar_all_path %>">Calendar</a> which shows all our class times and locations. If you click on an event it will actually give you an exact GPS link of where the class meets, as well as the cell phone number of the instructor.
  </p>

  <div class="faq-question">How Long Do Classes Last?</div>

  <p class="faq-answer">
    The majority of our classes are an hour and fifteen minutes long.
  </p>

  <div class="faq-question">Can I Get Reminders For Class?</div>

  <p class="faq-answer">
    You can manage your subscriptions (text and email alerts) within your <a href="<%= account_path %>">personal dashboard</a> in your Parkour Utah account. You can select reminders by clicking on individual classes in the calendar and selecting subscribe to this event.
  </p>

  <div class="faq-question">Why Is Open Gym Only 18 And Under?</div>

  <p class="faq-answer">
    The gym we rent on Friday nights has an insurance company that requires it. This doesn’t apply to workshops, seminars and parties we run there. Feel free to <a href="http://facebook.com/parkourutah">reach out to us on facebook</a> and we might be able to meet up with you at a local trampoline park or tumbling gym.
  </p>

  <div class="faq-question">I Want To Learn Flips!</div>

  <p class="faq-answer">
    Awesome! We'd love to help you learn whatever flip you'd like! We normally only teach flips at Open Gym or during seminars due to our access to pads and other safety equipment. Check out our Open Gyms on Friday nights.
  </p>

  <div class="faq-question">Isn't Parkour Dangerous?</div>

  <p class="faq-answer">
    Actually, the danger of parkour is often overestimated. Parkour has one of the lowest injury rates of all sports, way below baseball, football, basketball, etc... We also do what we can to mitigate risk and keep things safe. We've taught over 2,000 classes and have only had 2 injuries, that's an injury rate of 0.1%. Our students focus on safety and strength training; we rigorously test students before having them attempt any acrobatic movements.
  </p>

  <div class="faq-question">Do You Offer Private Lessons?</div>

  <p class="faq-answer">
    Absolutely! Just sign up in our store and it will allow you to request a specific instructor. As part of that process there is a general time table. After selecting a time the instructor will reach out to you and either confirm it or work out another time.
  </p>

  <div class="faq-question">What Services Do You Offer?</div>

  <p class="faq-answer">
    We have private lessons, outdoor parkour classes, indoor open gym, birthday parties, home-school events, seminars, jams and much more.
    <br>
    If you want to schedule something specific just <a href="<%= contact_path %>">contact us</a> or <a href="http://facebook.com/parkourutah">message us on facebook</a>.
  </p>

  <div class="faq-question">Do You Do Parkour Birthday Parties?</div>

  <p class="faq-answer">
    We most definitely do! We run both indoor and outdoor parties.
    <br>
    Message us <a href="<%= contact_path %>">here</a>, on <a href="http://facebook.com/parkourutah">facebook</a>, on <a href="http://twitter.com/parkourutah">twitter</a>, or on <a href="http://instagram.com/parkourutah">instagram</a> to schedule a birthday party, private seminar or specialized parkour meeting with us.
  </p>

  <div class="faq-question">Why Can't I Access The Store?</div>

  <p class="faq-answer">
    In order to purchase classes, private lessons, seminars and birthday parties we require you to have a Parkour Utah account. The account is free with no obligation. Part of the signup process includes the signing of our waiver. We do not allow participation without having a signed waiver.
    <br>
    You can still purchase clothing and gift card codes without an account.
  </p>
</div>

app/views/index/index.html.erb
  <div class="video-bg">
    <% unless mobile_device? %>
      <video autoplay="" loop="" muted="">
        <source src="<%= asset_path('pkut-bg-video.mov') %>" type="video/mp4">
      </video>
    <% end %>
  </div>
<div class="header-container" id="home">
  <div class="header vert">
    <div class="container">
      <%= image_tag('PKUT-full-color.png', class: 'img-responsive pkut-main center-block') %>
      <div>&nbsp;</div>
      <div class="call-nav">
        <a href="#about" class="main-btn lead scroll-link">About Us</a>
        <br class="visible-xs visible-sm"/>
        <% if user_signed_in? %>
          <a href="<%= account_path %>" class="main-btn lead call-to-arms">Get Started</a>
        <% else %>
          <a href="<%= new_user_path %>" class="main-btn lead call-to-arms">Get Started</a>
        <% end %>
        <br class="visible-xs visible-sm"/>
        <a href="#calendar" class="main-btn lead scroll-link">Locations</a>
        <a href="#join" class="main-btn lead scroll-link">Contact us</a>
      </div>
    </div>
  </div>
</div>

<div id="about" class="blurb">
  <div class="container">
    <div class="row">
      <h3>Welcome to Parkour Utah, Where Tricks Meet Technique, and Discipline Creates Flow!</h3>
      <p>At our parkour school, we believe that everyone—no matter their age or background—has the power to move with confidence, control and ultimate cool factor. Our expert coaches with over 40+ years of combined teaching experience guide students of all levels through the art of parkour in a safe, supportive, and inspiring environment. From curious and energy filled kids jumping for the first time, to adults rediscovering their inner athlete, we help every student unlock their full potential through dynamic movement, creative challenges, and a vibrant community. Join us, and turn the world into your playground!</p>
    </div>
  </div>
</div>

<div class="gallery" id="calendar">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h2 class="locations-text">Locations</h2>
      <br>
    </div>
  </div>

  <div class="container well well-lg">
    <div class="row">
      <% @cities.each do |city| %>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="list-group">
            <%= link_to city, calendar_show_path(city: city.parameterize), class: 'list-group-item locations-item' %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
</div>

<div class="blurb bright" id="join">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h2 class="contact-text"></h2>
      <br>
    </div>
  </div>
  <div class="row">
    <%= render partial: 'contact_us' %>
  </div>
</div>

<footer class="footer-index">
  <div class="container">
    <div class="row text-center">
      <div class="social-media-container">
        <a href="//facebook.com/ParkourUtah" target="_blank" class="social-media-icon">
          <%= image_tag "Facebook.png" %>
        </a>
        <a href="//youtube.com/ParkourUtah" target="_blank" class="social-media-icon">
          <%= image_tag "Youtube.png" %>
        </a>
        <a href="//twitter.com/ParkourUtah" target="_blank" class="social-media-icon">
          <%= image_tag "Twitter.png" %>
        </a>
      </div>
      <br>
      <div class="copyright">ParkourUtah © <%= Time.now.year %></div>
      </p>
    </div>
  </div>
</footer>

app/views/index/page_broken.html.erb
<div class="central-container error-div">
  <h1 class="lead"><%= @protocol %></h1>
  <div>Looks like there's nothing here.</div>
  <div>Click <%= link_to 'here', root_path %> to go back to the main page.</div>
</div>

app/views/index/page_not_found.html.erb
<div class="central-container error-div">
  <h1 class="lead"><%= @protocol %></h1>
  <div>Looks like there's nothing here.</div>
  <div>Click <%= link_to 'here', root_path %> to go back to the main page.</div>
</div>

app/views/index/unsubscribe.html.erb
<div class="central-container pkut-box form-offset">
  <h3>Enter your email below to unsubscribe.</h3>
  <h6>NOTE: We will no longer send emails to the email you entered, even if you've subscribed to class reminders or other notifications in the past.</h6>
  <%= form_tag unsubscribe_path do %>
    <div class="text-center">
      <%= email_field_tag :email, @user.try(:email), placeholder: 'Email Address', class: "pkut-textbox" %>

      <% if @unsubscribe_type.present? %>
        <div class="unsubscribe-btn-container">
          <%= radio_button_tag :unsubscribe_type, :all, checked: false %>
          <%= label_tag :unsubscribe_type_all, "Unsubscribe from All PKUT related emails" %>
        </div>
      <% end %>
      <% if @unsubscribe_type == :email_newsletter %>
        <div class="unsubscribe-btn-container">
          <%= radio_button_tag :unsubscribe_type, :email_newsletter, checked: false %>
          <%= label_tag :unsubscribe_type_email_newsletter, "Unsubscribe from Newsletters" %>
        </div>
      <% end %>
      <% if @unsubscribe_type == :email_class_reminder %>
        <div class="unsubscribe-btn-container">
          <%= radio_button_tag :unsubscribe_type, :email_class_reminder, checked: false %>
          <%= label_tag :unsubscribe_type_email_class_reminder, "Unsubscribe from Class Reminders" %>
        </div>
      <% end %>
      <% if @unsubscribe_type == :email_low_credits %>
        <div class="unsubscribe-btn-container">
          <%= radio_button_tag :unsubscribe_type, :email_low_credits, checked: false %>
          <%= label_tag :unsubscribe_type_email_low_credits, "Unsubscribe from Low Credits Notifications" %>
        </div>
      <% end %>
      <% if @unsubscribe_type == :email_waiver_expiring %>
        <div class="unsubscribe-btn-container">
          <%= radio_button_tag :unsubscribe_type, :email_waiver_expiring, checked: false %>
          <%= label_tag :unsubscribe_type_email_waiver_expiring, "Unsubscribe from Waiver Expiring Notifications" %>
        </div>
      <% end %>
      <% if @unsubscribe_type == :email_class_cancelled %>
        <div class="unsubscribe-btn-container">
          <%= radio_button_tag :unsubscribe_type, :email_class_cancelled, checked: false %>
          <%= label_tag :unsubscribe_type_email_class_cancelled, "Unsubscribe from Class Cancelled Notifications" %>
        </div>
      <% end %>
    </div>
    <div class="text-center">
      <%= submit_tag "Unsubscribe", class: "pkut-btn" %>
    </div>
  <% end %>
</div>