config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  match '404', to: 'index#page_not_found', via: :all
  match '422', to: 'index#page_not_found', via: :all
  match '500', to: 'index#page_broken', via: :all

  get :faq, to: "index#faq"

  get :flash_message, controller: "application"

  get 'talk' => 'index#get_request'
  post 'listen' => 'index#give_request'

  get 'freeplay' => 'users#freeplay'
  get 'register/step_2' => 'registrations#step_2', as: 'step_2'
  get 'register/step_3' => 'registrations#step_3', as: 'step_3'
  get 'register/step_4' => 'registrations#step_4', as: 'step_4'
  get 'register/step_5' => 'registrations#step_5', as: 'step_5'
  post 'register/step_2' => 'registrations#post_step_2'
  post 'register/step_3' => 'registrations#post_step_3'
  post 'register/step_4' => 'registrations#post_step_4'
  post 'register/step_4/fix' => 'registrations#fix_step_4', as: 'fix_review_page'
  post 'register/step_5' => 'registrations#post_step_5'

  # Websockets
  mount ActionCable.server => '/cable'

  resources :instructors do
    member do
      post :update_position
    end
  end

  get "/:slug" => "competitions#show", constraints: ->(request) { request.path_parameters[:slug].present? && Competition.from_slug(request.path_parameters[:slug]).present? }
  resources :competitions do
    get :export, on: :member
    get :monitor
    get :judge
    get :results
    get "judge/:category",              action: :category, as: :category
    get "judge/:category/:competitor_id",  action: :competitor, as: :competitor
    post "judge/:category/:competitor_id", action: :judge_competitor, as: :judge_competitor
  end
  resources :competitors, only: [:create, :update] do
    get :complete, on: :member
  end
  resources :spots
  resources :events, only: [ :show, :edit, :update ] do
    member do
      post :cancel
      get :detail
    end
  end
  resources :event_schedules, except: [ :destroy ] do
    get :contacts, on: :collection
    member do
      post :subscribe
      delete :unsubscribe
      post :send_message_to_subscribers
    end
  end

  resources :plan_items, except: [ :show, :destroy ]
  resources :line_items, except: [ :show ] do
    member do
      put :update_position
    end
  end

  resources :redemption_keys, except: [ :show, :edit, :update ] do
    member do
      get :redeem
    end
  end

  resources :class_handlers, path: 'class', only: [] do
    member do
      get :fast_pass_id
      get :fast_pass_pin
      get :logs
      post :join_class
    end
  end

  resources :announcements, except: [ :show ] do
    post :view, on: :collection
    post :deliver, on: :member
  end

  resources :attendances, only: [ :index, :new, :create, :destroy ]
  resources :aws_loggers, only: [ :index, :show ]
  resources :log_trackers, only: [ :index, :show ]
  resources :contact_requests, only: [ :index, :show ]
  resources :chat_rooms, path: "chat", only: [ :index, :show ] do
    get "phone_number/:phone_number", on: :collection, action: :by_phone_number, as: :phone_number
    post 'all/mark_messages_as_read', on: :collection, action: :mark_messages_as_read, as: :mark_messages_as_read
    resources :messages, only: [ :index ] do
      post :mark_messages_as_read, on: :collection
    end
  end

  get :dashboard, controller: :admins

  resource :admin, only: [] do
    get :purchase_history
    get :summary

    get :batch_text_message
    post :send_batch_texts

    get :email_body
    get :batch_email
    post :send_batch_emailer
  end

  resources :admin_users, path: "admin/users", only: [ :show, :index, :destroy ] do
    member do
      get :attendance
      get :unsubscribe_all
      post :update_trials
      post :update_credits
      post :update_notifications
    end
  end

  post 'contact' => 'index#contact'
  post 'receive_sms' => 'index#receive_sms'
  get 'contact' => 'index#contact_page', as: 'contact_page'
  post 'update' => 'index#update'
  get 'unsubscribe' => 'index#unsubscribe', as: 'unsubscribe_email'
  post 'unsubscribe' => 'index#unsubscribe_email', as: :unsubscribe
  post 'can_receive_sms' => 'index#can_receive_sms', as: 'make_can_receive_sms'

  delete 'unsubscribe_monthly/:id' => 'store#unsubscribe', as: 'unsubscribe_monthly_subscription'

  resources :athletes do
    member do
      post :reset_pin
      post :assign_plan
      delete :unsubscribe_plan
    end
    collection do
      post :verify
      post :assign_subscription
      patch :update_photo
    end
  end

  get 'waivers' => 'athletes#sign_waiver', as: 'waivers'
  post 'waivers' => 'athletes#update_waiver'
  post 'delete_athlete/:fast_pass_id' => 'athletes#delete_athlete'

  get "users/sign_up", action: "new", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  get "users/edit", action: "edit", controller: "users"
  resource :user, except: [ :show ] do
    post :update_card_details
  end
  devise_for :users
  devise_scope :user do
    get "/account" => "users#edit"
  end
  post 'user/notifications/update' => 'index#update_notifications'

  get "/calendar/all", to: redirect("/calendar")
  get 'calendar' => 'calendar#show', as: 'calendar_show'
  get 'calendar/week' => 'calendar#get_week', as: 'week'
  get 'm/calendar' => 'calendar#mobile', as: 'calendar_mobile'
  get 'calendar/:city' => 'calendar#show'

  post 'store/charge' => 'store#charge', as: 'charge'
  get 'store' => 'store#index', as: 'store'
  post 'store/redeem' => 'store#redeem'

  post 'cart/update' => 'store#update_cart', as: 'update_cart'
  post 'cart/purchase' => 'store#purchase', as: 'purchase'

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :still_signed_in
  before_action :validate_instructor, only: [ :show, :index, :attendance ]
  before_action :validate_admin, except: [ :show, :index, :attendance ]

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.order(created_at: :desc)
    @users = @users.by_fuzzy_text(params[:by_fuzzy_text]) if params[:by_fuzzy_text]
    @users = @users.page(params[:page])

    respond_to do |format|
      format.json { render json: @users.to_json(include: :athletes) }
      format.html
    end
  end

  def attendance
    @athletes = User[params[:id]].athletes
  end

  def unsubscribe_all
    user = User.find(params[:id])

    user.event_subscriptions.destroy_all

    redirect_to admin_user_path(user), notice: "Successfully unsubscribed user from all classes."
  end

  def update_notifications
    user = User.find(params[:id])
    user.notifications.blow!
    if params[:notify].present?
      params[:notify].each do |attribute, value|
        user.notifications.update(attribute => true)
      end
    end
    redirect_back fallback_location: root_path
  end

  def update_credits
    user = User.find(params[:id])
    user.credits += params[:adjust].to_i
    if user.save
      redirect_back fallback_location: root_path, notice: 'User successfully updated.'
    else
      redirect_back fallback_location: root_path, alert: 'There was a problem updating the user.'
    end
  end

  def update_trials
    user = User.find(params[:id])
    athlete = user.athletes.find(params[:fast_pass_id])
    if params[:num].to_i < 0
      params[:num].to_i.abs.times do
        athlete.trial.use!
      end
    else
      params[:num].to_i.abs.times do
        athlete.trial_classes.create
      end
    end
    redirect_back fallback_location: root_path
  end

  def destroy
    if params[:confirmation] == "DELETE"
      User.find(params[:id]).destroy
      redirect_to admin_users_path, notice: "User successfully deleted."
    else
      redirect_to admin_users_path, notice: "Sorry, DELETE was not entered correctly. User still exists."
    end
  end

end

app/views/admin_users/_edit_user_notifications.html.erb
<%= render_modal("edit_user_notifications") do %>
  <%= form_tag update_notifications_admin_user_path(@user) do %>
    <h1 class="pkut-text hidden-xs">Notifications</h1>
    <h4 class="pkut-text visible-xs">Notifications</h4>
    <p>Receive Notifications for:</p>
    <div class="row">
      <div class="col-xs-4">
      </div>
      <div class="col-xs-4">
        Email
      </div>
      <div class="col-xs-4">
        Text
      </div>
    </div>

    <div class="row">
      <div class="col-xs-4">
        Waiver Expiring
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[email_waiver_expiring]", '', @user.notifications.email_waiver_expiring? %>
          <%= label_tag "notify[email_waiver_expiring]", '' %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[text_waiver_expiring]", '', @user.notifications.text_waiver_expiring? %>
          <%= label_tag "notify[text_waiver_expiring]", '' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-4">
        Class Reminders
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[email_class_reminder]", '', @user.notifications.email_class_reminder? %>
          <%= label_tag "notify[email_class_reminder]", '' %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[text_class_reminder]", '', @user.notifications.text_class_reminder? %>
          <%= label_tag "notify[text_class_reminder]", '' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-4">
        Class Cancelled Message
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[email_class_cancelled]", '', @user.notifications.email_class_cancelled? %>
          <%= label_tag "notify[email_class_cancelled]", '' %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[text_class_cancelled]", '', @user.notifications.text_class_cancelled? %>
          <%= label_tag "notify[text_class_cancelled]", '' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-4">
        Low on credits
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[email_low_credits]", '', @user.notifications.email_low_credits? %>
          <%= label_tag "notify[email_low_credits]", '' %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[text_low_credits]", '', @user.notifications.text_low_credits? %>
          <%= label_tag "notify[text_low_credits]", '' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-4">
        Newsletter
      </div>
      <div class="col-xs-4">
        <div class="pkut-checkbox">
          <%= check_box_tag "notify[email_newsletter]", '', @user.notifications.email_newsletter? %>
          <%= label_tag "notify[email_newsletter]", '' %>
        </div>
      </div>
      <div class="col-xs-4"></div>
    </div>

    <% unless @user.can_receive_sms %>
      <div class="row" style="color: orange">
        <h4>You have blacklisted text notifications from ParkourUtah! You will not receive any text alerts.</h4>
        <h5>To un-blacklist us, simply text the word 'start' to +1 (844) 435-5867 and then click the button below.</h5>
        <h5>You should receive a text message saying you will now be able to receive text notifications from ParkourUtah.</h5>
      </div>
      <div class="row">
        <%= link_to 'Text Me!', make_can_receive_sms_path, class: 'pkut-btn', method: :post %>
      </div>
    <% end %>

    <%= submit_tag "Update", class: 'pkut-btn' %>
  <% end %>
<% end %>

app/views/admin_users/_edit_user_subscriptions.html.erb
<%= render_modal("edit_user_subscriptions") do %>
  <h1 class="pkut-header hidden-xs">Subscriptions</h1>
  <h4 class="pkut-header visible-xs">Subscriptions</h4>
  <% if @user.subscribed_athletes.any? %>
    <hr>
    <div class="row">
      <p>This user is currently set up to auto-pay for monthly subscriptions.</p>
      <% @user.subscribed_athletes.sort_by {|athlete|athlete.current_subscription.expires_at}.each do |athlete| %>
        <% subscription = athlete.current_subscription %>
        <div class="row">
          <div class="col-xs-6">
            <p>The next payment of <%= number_to_currency(subscription.cost) %> for <%= athlete.full_name %> will process on <%= (subscription.expires_at + 1.day).strftime('%B %e, %Y') %>.</p>
          </div>
          <div class="col-xs-6">
            <%= link_to 'Unsubscribe', unsubscribe_monthly_subscription_path(athlete.id), class: 'pkut-btn', method: :delete %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <% if @user.athletes_with_unlimited_access.count > 0 %>
    <hr>
    <% @user.athletes_with_unlimited_access.each do |athlete| %>
      <div class="row">
        <p><%= athlete.full_name %> has unlimited classes until: <%= athlete.current_subscription.expires_at.strftime('%B %e, %Y') %></p>
      </div>
    <% end %>
  <% end %>
  <% if @user.subscribed_events.any? %>
    <hr>
    <div class="row">
      <p>Classes subscribed to:</p>
      <% @user.subscribed_events.each do |schedule| %>
        <div class="row">
          <div class="col-xs-6">
            <%= schedule.city %> <%= schedule.title.capitalize %> <%= schedule.time_of_day %>
          </div>
          <div class="col-xs-6">
            <%= link_to 'Unsubscribe', unsubscribe_event_schedule_path(id: schedule.id, user_id: @user.id), class: 'pkut-btn', method: :delete %>
          </div>
        </div>
        <br/>
      <% end %>
    </div>
  <% end %>
  <% if @user.phone_number.present? %>
    <h3>Subscribe to class:</h3>
    <%= select_tag "event_token", options_for_select(EventSchedule.all.map { |es| [es.title, es.id] }), class: "pkut-dropdown subscribe-to-event-dropdown" %>
    <%= link_to 'Subscribe!', '', class: 'pkut-btn subscribe-to-selected-btn', method: :post, data: { new_href: subscribe_event_schedule_path(id: "--schedule_id--", user_id: @user.id) } %>
  <% else %>
    <p>Cannot subscribe to classes until User adds a valid phone number.</p>
  <% end %>
<% end %>

app/views/admin_users/attendance.html.erb
<div class="central-container form-offset">
  <%= link_to "Back to Dashboard", dashboard_path, class: 'pkut-btn' %><br><br>
  <%= link_to "Back to User Page", admin_user_path(params[:id]), class: 'pkut-btn' %>
  <h1>History</h1>
  <% @athletes.each do |athlete| %>
    <div class="athlete-history-container">
      <h4><%= athlete.full_name %> - ID: <%= athlete.fast_pass_id %></h4>
      <ul>
        <% athlete.attendances.by_most_recent(:created_at).each do |attendance| %>
        <li id="<%= attendance.id %>">
          <%= attendance.created_at.strftime('%B %-d, %Y') %> - <%= attendance.event ? attendance.event.title : 'This event was deleted' %><br>
          Host: <%= attendance.instructor.full_name %>
        </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/admin_users/index.html.erb
<div class="central-container form-offset">
  <%= link_to "Back to Dashboard", dashboard_path, class: 'pkut-btn' %><br/><br/>
  <%= text_field_tag :q, '', { id: "user_index_search_field", "data-index-url": admin_users_path, placeholder: "Search", class: "pkut-textbox" } %>
  <div>Users: <%= @users.total_count %></div>
  <div><%= paginate @users %></div>
  <% @users.each do |user| %>
    <h3><%= user.id %>: <%= '!' unless user.notifications.email_newsletter? %><%= user.email %></h3>
    <%= link_to 'View User Management Page', admin_user_path(user) %>
    <% if user.can_receive_sms? %>
      <p><strong><%= format_phone_number(user.phone_number) %></strong></p>
    <% else %>
      <p class="pkut-header"><s><%= format_phone_number(user.phone_number) %></s></p>
    <% end %>
    <p>Credits: <%= user.credits %>
    <p><a href="<%= attendance_admin_user_path(user) %>">Attendance History</a></p>
    <p>Last seen:
      <% if user.signed_in? %>
        <span style="color:green;">Online Now!</span>
      <% else %>
        <% if user.last_sign_in_at? %>
          <span style="color:yellow;"><%= (user.last_sign_in_at - 6.hours).strftime('%B %e, %Y at %I:%M %p') %></span>
        <% else %>
          <span style="color:red;">Never</span>
        <% end %>
      <% end %>
    </p>
    <p>Signed up: <strong><%= (user.created_at - 6.hours).strftime('%B %e, %Y at %I:%M %p') %></strong></p>
    <h4>Athletes:</h4>
    <% user.athletes_by_waiver_expiration.each do |athlete| %>
      <% if athlete.has_unlimited_access? %>
        <span style="color: green;">--Has unlimited access until: <%= athlete.has_access_until.strftime('%B %e, %Y') %></span><br/>
      <% end %>
        --<%= athlete.id %>: <strong><%= athlete.full_name %></strong> - ID: <%= athlete.fast_pass_id.to_s.rjust(4, "0") %><%= athlete.current_subscription.try(:auto_renew) ? '*' : '' %><br/>
      --Birthday: <%= athlete.date_of_birth %><br/>
      --Waiver expires: <%= athlete.waiver ? athlete.waiver.expiry_date.strftime('%B %e, %Y') : "No waiver signed" %><br/><br/>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/admin_users/show.html.erb
<div class="col-sm-offset-4">
  <br/>
  <%= link_to "Back to Dashboard", dashboard_path, class: 'pkut-btn' %><br/>
  <% if current_user.is_admin? %>
    <%= link_to "Back to Users Page", admin_users_path, class: 'pkut-btn' %><br/>
  <% end %>
  <%= link_to 'Back', :back, class: 'pkut-btn' %><br/>
  <h3><%= @user.id %>: <%= '!' unless @user.notifications.email_newsletter? %><%= @user.email %></h3>
  <%= link_to "Send Email", batch_email_admin_path(recipients: @user.email) if current_user.is_admin? %>
  <p>
    <% if @user.can_receive_sms? %>
      <strong><%= format_phone_number(@user.phone_number) %></strong>
      <% if current_user.is_admin? && @user.phone_number.present? %>
        <%= link_to("Send Text Message", phone_number_chat_rooms_path(@user.phone_number)) %>
      <% end %>
    <% else %>
      <s class="pkut-text"><%= format_phone_number(@user.phone_number) %></s>
    <% end %>
  </p>
  <% if current_user.is_admin? %>
    <p>Credits: <%= @user.credits %> -- <a data-toggle="modal" data-target="#adjust-<%= @user.id %>" class="forceOpen">Adjust</a></p>
    <p><a data-toggle="modal" data-target="#edit_user_notifications" class="forceOpen">Edit Notifications</a></p>
    <p><a data-toggle="modal" data-target="#edit_user_subscriptions" class="forceOpen">Edit Subscriptions</a></p>
    <p><a href="<%= attendance_admin_user_path(@user) %>">Attendance History</a></p>
    <p>Last seen:
      <% if @user.signed_in? %>
        <span style="color:green;">Online Now!</span>
      <% else %>
        <% if @user.last_sign_in_at? %>
          <span style="color:yellow;"><%= (@user.last_sign_in_at - 6.hours).strftime('%B %e, %Y at %I:%M %p') %></span>
        <% else %>
          <span style="color:red;">Never</span>
        <% end %>
      <% end %>
    </p>
    <p>Signed up: <strong><%= (@user.created_at - 6.hours).strftime('%B %e, %Y at %I:%M %p') %></strong></p>
  <% end %>
  <h4>Athletes:</h4>
  <% @user.athletes_by_waiver_expiration.each do |athlete| %>
    <% if athlete.has_unlimited_access? %>
      <span style="color: green;">--Has unlimited access until: <%= athlete.has_access_until.strftime('%B %e, %Y') %></span><br/>
    <% end %>
    --<strong><%= athlete.full_name %></strong> - Fast Pass ID: <%= athlete.fast_pass_id.to_s.rjust(4, "0") %><%= athlete.current_subscription.try(:auto_renew) ? '*' : '' %><br/>
    <% if athlete.unused_trials.count > 0 %>
      --Has <%= athlete.unused_trials.count %> trial class(es) remaining. <%= link_to 'Remove 1 Trial', update_trials_admin_user_path(@user, fast_pass_id: athlete.id, num: '-1'), method: :post if current_user.is_admin? %>
      <br/>
    <% end %>
    <% if current_user.is_admin? %>
      --<%= link_to 'Add Trial Class', update_trials_admin_user_path(@user, fast_pass_id: athlete.id, num: '1'), method: :post %><br/>
    <% end %>

    <%= render_modal("edit#{athlete.id}", "skinny-modal") do %>
      <h3 class="pkut-text"><%= athlete.full_name %></h3>
      <p>This will permanently delete this athlete. Are you sure? This action cannot be undone.<p>
      <%= link_to "Delete", athlete_path(athlete.id), class: 'pkut-btn', method: :delete %>
    <% end %>

    --Birthday: <%= athlete.date_of_birth %><br/>
    --Waiver expires: <%= athlete.waiver ? athlete.waiver.expiry_date.strftime('%B %e, %Y') : "No waiver signed" %><br/>
    <% if current_user.is_admin? %>
      --<a alt="..." class="pkut-text forceOpen" data-toggle="modal" data-target="#edit<%= athlete.id %>">Delete Athlete</a><br/><br/>
    <% end %>
    <% if false %>
      --<%= link_to 'Curriculum', '' %><br>
    <% end %>
    <br>
  <% end %>
  <br/>
  <br/>
  <br/>
  <% if current_user.is_admin? %>
    <a data-toggle="modal" data-target="#delete-<%= @user.id %>" class="pkut-btn forceOpen">Delete User</a>
  <% end %>
</div>
<hr>

<%= render_modal("adjust-#{@user.id}", "skinny-modal") do %>
  <h1 class="pkut-text">Adjust</h1>
  <p class="error-message">Enter a number to add credits to user's account. Enter a (-) before the number to subtract credits.</p>
  <p class="error-message">(12 or -12)</p>
  <%= form_tag update_credits_admin_user_path(@user) do %>
    <%= text_field_tag :adjust, '' %>
    <%= submit_tag "Adjust Credits", class: 'pkut-btn' %>
  <% end %>
<% end %>

<%= render_modal("delete-#{@user.id}", "skinny-modal") do %>
  <h1 class="pkut-text">Destroy?</h1>
  <p class="error-message">Are you positive you want to destroy <strong><%= @user.full_name %></strong>?</p>
  <p class="error-message">This is permanent and cannot be undone.</p>
  <p class="error-message">If you are sure, enter `DELETE`(all caps, no quotes) below and then click delete user.</p>
  <%= form_for [:admin, @user], method: :delete do %>
    <%= text_field_tag :confirmation, '', class: 'delete-user-field'  %>
    <%= submit_tag "Delete User", class: 'delete-user-btn' %>
  <% end %>
<% end %>

<%= render partial: 'edit_user_notifications', locals: {user: @user} %>
<%= render partial: 'edit_user_subscriptions', locals: {user: @user} %>